In [1]:
import pandas as pd

In [4]:
df1 = pd.read_csv("Book(Sheet1).csv")
df1.head()

  age_group  income
0     31-45   40000
1     22-30   25000
2     46-55  120000
3     56-60  500000

In [5]:
df1.age_group.unique()

<StringArray>
['31-45', '22-30', '46-55', '56-60']
Length: 4, dtype: str

In [6]:
df1.groupby(df1.age_group).count()

           income
age_group
22-30           1
31-45           1
46-55           1
56-60           1

In [7]:
df1.groupby(df1.age_group).min()

           income
age_group
22-30       25000
31-45       40000
46-55      120000
56-60      500000

In [8]:
df1.groupby(df1.age_group).max()

           income
age_group
22-30       25000
31-45       40000
46-55      120000
56-60      500000

In [9]:
df1.groupby(df1.age_group).mean()

             income
age_group
22-30       25000.0
31-45       40000.0
46-55      120000.0
56-60      500000.0

In [10]:
df1.groupby(df1.age_group).std()

           income
age_group
22-30         NaN
31-45         NaN
46-55         NaN
56-60         NaN

In [11]:
df1.groupby(df1.age_group).describe()

          income                                                        \
           count      mean std       min       25%       50%       75%
age_group
22-30        1.0   25000.0 NaN   25000.0   25000.0   25000.0   25000.0
31-45        1.0   40000.0 NaN   40000.0   40000.0   40000.0   40000.0
46-55        1.0  120000.0 NaN  120000.0  120000.0  120000.0  120000.0
56-60        1.0  500000.0 NaN  500000.0  500000.0  500000.0  500000.0


                max
age_group
22-30       25000.0
31-45       40000.0
46-55      120000.0
56-60      500000.0